name: flutter_bloc_ca
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  cloud_firestore: ^4.8.2
  dio: ^5.2.1+1
  equatable: ^2.0.5
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.8.4
  fpdart: ^0.6.0
  get_it: ^7.6.0
  go_router: ^9.0.0
  google_fonts: ^5.1.0
  logger: ^1.4.0
  internet_connection_checker: ^1.0.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^8.0.0
  hydrated_bloc: ^9.1.2
  path_provider: ^2.0.15
  easy_localization: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
